-- Dolly POS - Complete Database Schema DDL
-- Dolly Toys & Kids Wear, Dhule

CREATE TABLE categories (
	id SERIAL NOT NULL, 
	name VARCHAR(100) NOT NULL, 
	description VARCHAR(255), 
	icon VARCHAR(50), 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (id)
);

CREATE TABLE customers (
	id SERIAL NOT NULL, 
	name VARCHAR(100) NOT NULL, 
	phone VARCHAR(20), 
	alt_phone VARCHAR(20), 
	email VARCHAR(100), 
	address TEXT, 
	city VARCHAR(50), 
	date_of_birth VARCHAR(20), 
	anniversary_date VARCHAR(20), 
	credit_balance FLOAT NOT NULL, 
	total_spend FLOAT NOT NULL, 
	visit_count INTEGER NOT NULL, 
	favorite_category VARCHAR(100), 
	notes TEXT, 
	is_active BOOLEAN NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	last_visit_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id)
);

CREATE TABLE lost_demand_logs (
	id SERIAL NOT NULL, 
	item_description VARCHAR(255) NOT NULL, 
	category_name VARCHAR(100), 
	preferred_size VARCHAR(50), 
	preferred_color VARCHAR(50), 
	customer_name VARCHAR(100), 
	customer_phone VARCHAR(20), 
	request_count INTEGER NOT NULL, 
	urgency lostdemandurgency NOT NULL, 
	status lostdemandstatus NOT NULL, 
	notes TEXT, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (id)
);

CREATE TABLE procurement_notes (
	id SERIAL NOT NULL, 
	item_name VARCHAR(255) NOT NULL, 
	quantity INTEGER NOT NULL, 
	description TEXT, 
	vendor_name VARCHAR(255), 
	estimated_price FLOAT, 
	priority VARCHAR(50) NOT NULL, 
	status VARCHAR(50) NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (id)
);

CREATE TABLE store_settings (
	id SERIAL NOT NULL, 
	shop_name VARCHAR(150) NOT NULL, 
	tag_line VARCHAR(200), 
	is_tagline_bold BOOLEAN NOT NULL, 
	address TEXT NOT NULL, 
	mobile VARCHAR(20) NOT NULL, 
	alt_mobile VARCHAR(20), 
	active_purge_token VARCHAR(500), 
	email VARCHAR(100), 
	gstin VARCHAR(20), 
	show_gst_on_bill BOOLEAN NOT NULL, 
	upi_id VARCHAR(100) NOT NULL, 
	show_upi_qr_on_bill BOOLEAN NOT NULL, 
	opening_date VARCHAR(50), 
	bill_prefix VARCHAR(20), 
	bill_header TEXT, 
	bill_footer TEXT, 
	footer_font_size VARCHAR(20), 
	is_footer_bold BOOLEAN NOT NULL, 
	power_footer_text VARCHAR(255), 
	power_footer_font_size VARCHAR(20), 
	is_power_footer_bold BOOLEAN NOT NULL, 
	terms_and_conditions TEXT, 
	show_terms_on_bill BOOLEAN NOT NULL, 
	whatsapp_bill_template TEXT, 
	custom_festival_items TEXT, 
	instagram_handle VARCHAR(100), 
	show_instagram_on_bill BOOLEAN NOT NULL, 
	facebook_handle VARCHAR(150), 
	show_facebook_on_bill BOOLEAN NOT NULL, 
	threads_handle VARCHAR(100), 
	show_threads_on_bill BOOLEAN NOT NULL, 
	website_url VARCHAR(150), 
	show_website_on_bill BOOLEAN NOT NULL, 
	custom_social_label VARCHAR(50), 
	custom_social_handle VARCHAR(150), 
	show_custom_social_on_bill BOOLEAN NOT NULL, 
	custom_social_label2 VARCHAR(50), 
	custom_social_handle2 VARCHAR(150), 
	show_custom_social_on_bill2 BOOLEAN NOT NULL, 
	custom_social_label3 VARCHAR(50), 
	custom_social_handle3 VARCHAR(150), 
	show_custom_social_on_bill3 BOOLEAN NOT NULL, 
	custom_social_label4 VARCHAR(50), 
	custom_social_handle4 VARCHAR(150), 
	show_custom_social_on_bill4 BOOLEAN NOT NULL, 
	custom_social_label5 VARCHAR(50), 
	custom_social_handle5 VARCHAR(150), 
	show_custom_social_on_bill5 BOOLEAN NOT NULL, 
	thermal_printer_name VARCHAR(100), 
	thermal_width VARCHAR(10) NOT NULL, 
	barcode_printer_name VARCHAR(100), 
	barcode_label_size VARCHAR(20) NOT NULL, 
	theme_mode VARCHAR(10) NOT NULL, 
	sound_enabled BOOLEAN NOT NULL, 
	auto_backup BOOLEAN NOT NULL, 
	backup_frequency VARCHAR(20) NOT NULL, 
	backup_path VARCHAR(255), 
	backup_filename_prefix VARCHAR(100) NOT NULL, 
	google_drive_connected BOOLEAN NOT NULL, 
	google_drive_email VARCHAR(150), 
	google_drive_folder_id VARCHAR(100), 
	google_drive_refresh_token TEXT, 
	google_drive_access_token TEXT, 
	google_drive_token_expires_at TIMESTAMP WITHOUT TIME ZONE, 
	google_client_id VARCHAR(255), 
	google_client_secret VARCHAR(255), 
	backup_destination VARCHAR(50) NOT NULL, 
	backup_on_app_close BOOLEAN NOT NULL, 
	backup_retention_days INTEGER NOT NULL, 
	last_cloud_backup_at TIMESTAMP WITHOUT TIME ZONE, 
	extra_charge_enabled_1 BOOLEAN NOT NULL, 
	extra_charge_name_1 VARCHAR(100), 
	extra_charge_condition_1 VARCHAR(50), 
	extra_charge_threshold_1 FLOAT, 
	extra_charge_type_1 VARCHAR(20), 
	extra_charge_value_1 FLOAT, 
	extra_charge_payment_mode_1 VARCHAR(50), 
	extra_charge_enabled_2 BOOLEAN NOT NULL, 
	extra_charge_name_2 VARCHAR(100), 
	extra_charge_condition_2 VARCHAR(50), 
	extra_charge_threshold_2 FLOAT, 
	extra_charge_type_2 VARCHAR(20), 
	extra_charge_value_2 FLOAT, 
	extra_charge_payment_mode_2 VARCHAR(50), 
	extra_charge_enabled_3 BOOLEAN NOT NULL, 
	extra_charge_name_3 VARCHAR(100), 
	extra_charge_condition_3 VARCHAR(50), 
	extra_charge_threshold_3 FLOAT, 
	extra_charge_type_3 VARCHAR(20), 
	extra_charge_value_3 FLOAT, 
	extra_charge_payment_mode_3 VARCHAR(50), 
	extra_charge_enabled_4 BOOLEAN NOT NULL, 
	extra_charge_name_4 VARCHAR(100), 
	extra_charge_condition_4 VARCHAR(50), 
	extra_charge_threshold_4 FLOAT, 
	extra_charge_type_4 VARCHAR(20), 
	extra_charge_value_4 FLOAT, 
	extra_charge_payment_mode_4 VARCHAR(50), 
	extra_charge_enabled_5 BOOLEAN NOT NULL, 
	extra_charge_name_5 VARCHAR(100), 
	extra_charge_condition_5 VARCHAR(50), 
	extra_charge_threshold_5 FLOAT, 
	extra_charge_type_5 VARCHAR(20), 
	extra_charge_value_5 FLOAT, 
	extra_charge_payment_mode_5 VARCHAR(50), 
	store_id VARCHAR(50), 
	store_token VARCHAR(30), 
	store_secret VARCHAR(100), 
	cloud_sync_enabled BOOLEAN NOT NULL, 
	cloud_hub_url VARCHAR(255) NOT NULL, 
	last_cloud_sync_at TIMESTAMP WITHOUT TIME ZONE, 
	cloud_sync_status VARCHAR(50) NOT NULL, 
	cloud_sync_error TEXT, 
	updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (id)
);

CREATE TABLE users (
	id SERIAL NOT NULL, 
	username VARCHAR(50) NOT NULL, 
	password_hash VARCHAR(255) NOT NULL, 
	plain_password VARCHAR(255), 
	full_name VARCHAR(100) NOT NULL, 
	role userrole NOT NULL, 
	is_active BOOLEAN NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	last_login TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id)
);

CREATE TABLE vendors (
	id SERIAL NOT NULL, 
	vendor_code VARCHAR(20), 
	name VARCHAR(100) NOT NULL, 
	company_name VARCHAR(150), 
	phone VARCHAR(20) NOT NULL, 
	alt_phone VARCHAR(20), 
	email VARCHAR(100), 
	gstin VARCHAR(20), 
	address TEXT, 
	city VARCHAR(50), 
	state VARCHAR(50), 
	notes TEXT, 
	bank_name VARCHAR(100), 
	bank_account_no VARCHAR(50), 
	bank_ifsc VARCHAR(20), 
	bank_holder_name VARCHAR(100), 
	vendor_upi_id VARCHAR(100), 
	outstanding_due FLOAT NOT NULL, 
	is_active BOOLEAN NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (id)
);

CREATE TABLE whatsapp_config (
	id SERIAL NOT NULL, 
	store_phone VARCHAR(20) NOT NULL, 
	store_name VARCHAR(100) NOT NULL, 
	provider whatsappprovider NOT NULL, 
	meta_api_token TEXT, 
	meta_phone_number_id VARCHAR(100), 
	meta_business_account_id VARCHAR(100), 
	is_connected BOOLEAN NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (id)
);

CREATE TABLE whatsapp_logs (
	id SERIAL NOT NULL, 
	recipient_name VARCHAR(100), 
	recipient_phone VARCHAR(20) NOT NULL, 
	message_type whatsappmessagetype NOT NULL, 
	message_text TEXT NOT NULL, 
	status whatsappstatus NOT NULL, 
	error_message TEXT, 
	sent_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (id)
);

CREATE TABLE audit_logs (
	id SERIAL NOT NULL, 
	user_id INTEGER, 
	action_type VARCHAR(50) NOT NULL, 
	entity VARCHAR(50) NOT NULL, 
	entity_id VARCHAR(50), 
	details_json TEXT, 
	ip_address VARCHAR(50), 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE SET NULL
);

CREATE TABLE customer_ledger (
	id SERIAL NOT NULL, 
	customer_id INTEGER NOT NULL, 
	entry_type customerledgertype NOT NULL, 
	reference_no VARCHAR(100), 
	debit_amount FLOAT NOT NULL, 
	credit_amount FLOAT NOT NULL, 
	balance_after FLOAT NOT NULL, 
	payment_mode VARCHAR(50), 
	notes TEXT, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(customer_id) REFERENCES customers (id) ON DELETE CASCADE
);

CREATE TABLE expenses (
	id SERIAL NOT NULL, 
	category expensecategory NOT NULL, 
	title VARCHAR(150) NOT NULL, 
	amount FLOAT NOT NULL, 
	payment_mode VARCHAR(50) NOT NULL, 
	paid_to VARCHAR(100), 
	notes TEXT, 
	expense_date TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	logged_by INTEGER, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(logged_by) REFERENCES users (id) ON DELETE SET NULL
);

CREATE TABLE invoices (
	id SERIAL NOT NULL, 
	bill_number VARCHAR(50) NOT NULL, 
	customer_id INTEGER, 
	cashier_id INTEGER, 
	subtotal FLOAT NOT NULL, 
	discount_amount FLOAT NOT NULL, 
	discount_type VARCHAR(20) NOT NULL, 
	tax_amount FLOAT NOT NULL, 
	cgst_amount FLOAT NOT NULL, 
	sgst_amount FLOAT NOT NULL, 
	extra_charges_amount FLOAT NOT NULL, 
	extra_charges_breakdown TEXT, 
	round_off FLOAT NOT NULL, 
	grand_total FLOAT NOT NULL, 
	paid_amount FLOAT NOT NULL, 
	change_amount FLOAT NOT NULL, 
	due_amount FLOAT NOT NULL, 
	payment_mode paymentmode NOT NULL, 
	payment_status paymentstatus NOT NULL, 
	is_held BOOLEAN NOT NULL, 
	is_cancelled BOOLEAN NOT NULL, 
	is_gift_receipt BOOLEAN NOT NULL, 
	customer_name VARCHAR(100), 
	customer_phone VARCHAR(20), 
	notes TEXT, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(customer_id) REFERENCES customers (id) ON DELETE SET NULL, 
	FOREIGN KEY(cashier_id) REFERENCES users (id) ON DELETE SET NULL
);

CREATE TABLE purchases (
	id SERIAL NOT NULL, 
	purchase_number VARCHAR(50) NOT NULL, 
	vendor_id INTEGER NOT NULL, 
	supplier_invoice_no VARCHAR(100), 
	invoice_date TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	subtotal FLOAT NOT NULL, 
	tax_amount FLOAT NOT NULL, 
	discount_amount FLOAT NOT NULL, 
	shipping_charges FLOAT NOT NULL, 
	total_amount FLOAT NOT NULL, 
	paid_amount FLOAT NOT NULL, 
	due_amount FLOAT NOT NULL, 
	status purchasestatus NOT NULL, 
	payment_status purchasepaymentstatus NOT NULL, 
	notes TEXT, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(vendor_id) REFERENCES vendors (id) ON DELETE CASCADE
);

CREATE TABLE subcategories (
	id SERIAL NOT NULL, 
	category_id INTEGER NOT NULL, 
	name VARCHAR(100) NOT NULL, 
	description VARCHAR(255), 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(category_id) REFERENCES categories (id) ON DELETE CASCADE
);

CREATE TABLE vendor_ledger (
	id SERIAL NOT NULL, 
	vendor_id INTEGER NOT NULL, 
	entry_type vendorledgertype NOT NULL, 
	reference_no VARCHAR(100), 
	debit_amount FLOAT NOT NULL, 
	credit_amount FLOAT NOT NULL, 
	balance_after FLOAT NOT NULL, 
	payment_mode VARCHAR(50), 
	notes TEXT, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(vendor_id) REFERENCES vendors (id) ON DELETE CASCADE
);

CREATE TABLE payments (
	id SERIAL NOT NULL, 
	invoice_id INTEGER NOT NULL, 
	payment_mode paymentmode NOT NULL, 
	amount FLOAT NOT NULL, 
	transaction_ref VARCHAR(100), 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(invoice_id) REFERENCES invoices (id) ON DELETE CASCADE
);

CREATE TABLE products (
	id SERIAL NOT NULL, 
	barcode VARCHAR(50) NOT NULL, 
	sku VARCHAR(50), 
	manufacture_code VARCHAR(50), 
	vendor_code VARCHAR(50), 
	name VARCHAR(200) NOT NULL, 
	category_id INTEGER, 
	subcategory_id INTEGER, 
	brand VARCHAR(100), 
	gender VARCHAR(30), 
	age_group VARCHAR(50), 
	size VARCHAR(50), 
	color VARCHAR(50), 
	fabric VARCHAR(100), 
	season VARCHAR(50), 
	tags VARCHAR(255), 
	description TEXT, 
	purchase_price FLOAT NOT NULL, 
	selling_price FLOAT NOT NULL, 
	mrp FLOAT NOT NULL, 
	gst_percent FLOAT NOT NULL, 
	cgst_percent FLOAT NOT NULL, 
	sgst_percent FLOAT NOT NULL, 
	margin_percent FLOAT NOT NULL, 
	stock_quantity INTEGER NOT NULL, 
	min_stock_alert INTEGER NOT NULL, 
	damaged_quantity INTEGER NOT NULL, 
	location_shelf VARCHAR(50), 
	is_speed_dial BOOLEAN NOT NULL, 
	speed_dial_code VARCHAR(20), 
	speed_dial_color VARCHAR(20), 
	is_active BOOLEAN NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	last_purchased_at TIMESTAMP WITHOUT TIME ZONE, 
	last_sold_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	FOREIGN KEY(category_id) REFERENCES categories (id) ON DELETE SET NULL, 
	FOREIGN KEY(subcategory_id) REFERENCES subcategories (id) ON DELETE SET NULL
);

CREATE TABLE returns (
	id SERIAL NOT NULL, 
	return_number VARCHAR(50) NOT NULL, 
	invoice_id INTEGER, 
	customer_id INTEGER, 
	cashier_id INTEGER, 
	total_refund_amount FLOAT NOT NULL, 
	return_type returntype NOT NULL, 
	reason VARCHAR(255), 
	notes TEXT, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(invoice_id) REFERENCES invoices (id) ON DELETE SET NULL, 
	FOREIGN KEY(customer_id) REFERENCES customers (id) ON DELETE SET NULL, 
	FOREIGN KEY(cashier_id) REFERENCES users (id) ON DELETE SET NULL
);

CREATE TABLE invoice_items (
	id SERIAL NOT NULL, 
	invoice_id INTEGER NOT NULL, 
	product_id INTEGER, 
	item_name VARCHAR(200) NOT NULL, 
	barcode VARCHAR(50), 
	sku VARCHAR(50), 
	size VARCHAR(50), 
	color VARCHAR(50), 
	quantity INTEGER NOT NULL, 
	unit_price FLOAT NOT NULL, 
	cost_price FLOAT NOT NULL, 
	discount_amount FLOAT NOT NULL, 
	tax_percent FLOAT NOT NULL, 
	tax_amount FLOAT NOT NULL, 
	cgst_percent FLOAT NOT NULL, 
	cgst_amount FLOAT NOT NULL, 
	sgst_percent FLOAT NOT NULL, 
	sgst_amount FLOAT NOT NULL, 
	total_price FLOAT NOT NULL, 
	is_unlisted BOOLEAN NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(invoice_id) REFERENCES invoices (id) ON DELETE CASCADE, 
	FOREIGN KEY(product_id) REFERENCES products (id) ON DELETE SET NULL
);

CREATE TABLE product_price_history (
	id SERIAL NOT NULL, 
	product_id INTEGER NOT NULL, 
	old_purchase_price FLOAT, 
	new_purchase_price FLOAT, 
	old_selling_price FLOAT, 
	new_selling_price FLOAT, 
	old_mrp FLOAT, 
	new_mrp FLOAT, 
	reason VARCHAR(200), 
	changed_by VARCHAR(100), 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(product_id) REFERENCES products (id) ON DELETE CASCADE
);

CREATE TABLE purchase_items (
	id SERIAL NOT NULL, 
	purchase_id INTEGER NOT NULL, 
	product_id INTEGER NOT NULL, 
	product_name VARCHAR(200) NOT NULL, 
	barcode VARCHAR(50), 
	quantity INTEGER NOT NULL, 
	cost_price FLOAT NOT NULL, 
	selling_price FLOAT NOT NULL, 
	gst_percent FLOAT NOT NULL, 
	total_cost FLOAT NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(purchase_id) REFERENCES purchases (id) ON DELETE CASCADE, 
	FOREIGN KEY(product_id) REFERENCES products (id) ON DELETE CASCADE
);

CREATE TABLE return_items (
	id SERIAL NOT NULL, 
	return_id INTEGER NOT NULL, 
	product_id INTEGER, 
	item_name VARCHAR(200) NOT NULL, 
	barcode VARCHAR(50), 
	quantity INTEGER NOT NULL, 
	refund_price FLOAT NOT NULL, 
	tax_percent FLOAT NOT NULL, 
	tax_amount FLOAT NOT NULL, 
	cgst_percent FLOAT NOT NULL, 
	cgst_amount FLOAT NOT NULL, 
	sgst_percent FLOAT NOT NULL, 
	sgst_amount FLOAT NOT NULL, 
	is_defective BOOLEAN NOT NULL, 
	restocked BOOLEAN NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(return_id) REFERENCES returns (id) ON DELETE CASCADE, 
	FOREIGN KEY(product_id) REFERENCES products (id) ON DELETE SET NULL
);

